# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'election.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\"%\n\x0f\x45lectionRequest\x12\x12\n\nelectionId\x18\x01 \x01(\t\"5\n\rCandidateData\x12\x15\n\rcandidateName\x18\x01 \x01(\t\x12\r\n\x05votes\x18\x02 \x01(\x05\"J\n\x10\x45lectionResponse\x12\x12\n\nelectionId\x18\x01 \x01(\t\x12\"\n\ncandidates\x18\x02 \x03(\x0b\x32\x0e.CandidateData2K\n\x0f\x45lectionService\x12\x38\n\x0fgetElectionData\x12\x10.ElectionRequest\x1a\x11.ElectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=18
  _globals['_ELECTIONREQUEST']._serialized_end=55
  _globals['_CANDIDATEDATA']._serialized_start=57
  _globals['_CANDIDATEDATA']._serialized_end=110
  _globals['_ELECTIONRESPONSE']._serialized_start=112
  _globals['_ELECTIONRESPONSE']._serialized_end=186
  _globals['_ELECTIONSERVICE']._serialized_start=188
  _globals['_ELECTIONSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
